### ISSUE TITLE
Application getting stuck on entering wrong url to API endpoint.

### ISSUE THREAD

**Issue by agbilotia1998** [fossasia/open-event-webapp#1440]
**Actual Behaviour**

The application gets stuck when wrong url is entered to API endpoint also the logs oce give error and then success message that json files are downloaded.

**Expected Behaviour**

The app should throw an error pointing that wrong url is entered and the logs should not show the success message.

**Steps to reproduce it**
Enter any wrong link to API endpoint and click on generate webapp button.
**Log for the issue**

Provide console logs for the issue here
Error: Response = 503received
    at Request.<anonymous> (/home/ayush/WebstormProjects/openEventWebapp/open-event-webapp/src/backend/dist.js:87:14)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Request.onRequestResponse (/home/ayush/WebstormProjects/openEventWebapp/open-event-webapp/node_modules/request/request.js:1074:10)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:454:20)

Where-ever possible add a screenshot of the issue.
![screenshot from 2017-08-15 15-47-51](https://user-images.githubusercontent.com/21157929/29312184-e03149ea-81d1-11e7-93e5-2c2296e5dee3.png)

**Would you like to work on the issue?**
Yes I would like to work on it.

Let us know if this issue should be assigned to you or tell us who you think could help to solve this issue.

**Comment by Princu7** [comment]
@agbilotia1998 Thank you so much! Please go ahead!
