### ISSUE TITLE
Can not run on local

### ISSUE THREAD

**Issue by rockerhieu** [fossasia/open-event-webapp#1748]
**Actual Behaviour**

As soon as I open localhost:5000, the server crash.

**Expected Behaviour**

I should be able to use the app at localhost:5000

**Steps to reproduce it**

npm install
npm start

**Log for the issue**

```
npm run start

> open-event-webapp@2.0.0 start /Users/rockr/Development/personal/open-event-webapp
> npm run server.generator


> open-event-webapp@2.0.0 server.generator /Users/rockr/Development/personal/open-event-webapp
> node src/app.js

Node app is running on port 5000
/Users/rockr/Development/personal/open-event-webapp/node_modules/connect-domain/lib/connect-domain.js:17
			reqDomain.dispose();
			          ^

TypeError: reqDomain.dispose is not a function
    at Domain.<anonymous> (/Users/rockr/Development/personal/open-event-webapp/node_modules/connect-domain/lib/connect-domain.js:17:14)
    at Domain.emit (events.js:160:13)
    at Domain._errorHandler (domain.js:198:23)
    at Object.setUncaughtExceptionCaptureCallback (domain.js:114:29)
    at process._fatalException (bootstrap_node.js:381:31)
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! open-event-webapp@2.0.0 server.generator: `node src/app.js`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the open-event-webapp@2.0.0 server.generator script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rockr/.npm/_logs/2018-03-04T05_11_33_870Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! open-event-webapp@2.0.0 start: `npm run server.generator`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the open-event-webapp@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rockr/.npm/_logs/2018-03-04T05_11_33_900Z-debug.log
```

**Comment by shubham3211** [comment]
I don't think it is a valid issue as I am able to deploy it on localhost:5000. 
If you have any problem please come to our gitter channel :- https://gitter.im/fossasia/open-event-webapp
and we will try to help you.

**Comment by rockerhieu** [comment]
I can deploy it on localhost:5000, but as soon as I open the website, it crash. I did change the config for sendgrid, smtp2go, aws s3 and leave the github configuration untouched. Do I need to change any other config before running the app?

**Comment by harsh-98** [comment]
If still not working try changing the version of `connect-domain` in package.json and running `npm run start` again.

**Comment by ParthS007** [comment]
closing it as running on local :+1:
