### ISSUE TITLE
Errors when running the web app

### ISSUE THREAD

**Issue by oren** [fossasia/open-event-webapp#187]
The first error in the console is `      if (scope.tweetNumber !=== 90) {
` which make sense since !=== is not valid. (https://github.com/fossasia/open-event-webapp/blob/master/src/appComponents/twitterwall/singletweet.js#L58) I fixed it to !== but no I see this error: 
```
SessionsController.js:23 Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module openevent due to:
Error: [$injector:modulerr] Failed to instantiate module oe.sessions due to:
Error: [$injector:nomod] Module 'oe.sessions' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.5/$injector/nomod?p0=oe.sessions
    at http://localhost:8080/libs/angular.js:68:12
    at http://localhost:8080/libs/angular.js:2070:17
    at ensure (http://localhost:8080/libs/angular.js:1994:38)
    at module (http://localhost:8080/libs/angular.js:2068:14)
    at http://localhost:8080/libs/angular.js:4564:22
    at forEach (http://localhost:8080/libs/angular.js:322:20)
    at loadModules (http://localhost:8080/libs/angular.js:4548:5)
    at http://localhost:8080/libs/angular.js:4565:40
    at forEach (http://localhost:8080/libs/angular.js:322:20)
    at loadModules (http://localhost:8080/libs/angular.js:4548:5)
http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=oe.sessions&p1=Erro…oadModules%20(http%3A%2F%2Flocalhost%3A8080%2Flibs%2Fangular.js%3A4548%3A5)
    at http://localhost:8080/libs/angular.js:68:12
    at http://localhost:8080/libs/angular.js:4587:15
    at forEach (http://localhost:8080/libs/angular.js:322:20)
    at loadModules (http://localhost:8080/libs/angular.js:4548:5)
    at http://localhost:8080/libs/angular.js:4565:40
    at forEach (http://localhost:8080/libs/angular.js:322:20)
    at loadModules (http://localhost:8080/libs/angular.js:4548:5)
    at createInjector (http://localhost:8080/libs/angular.js:4470:19)
    at doBootstrap (http://localhost:8080/libs/angular.js:1746:20)
    at bootstrap (http://localhost:8080/libs/angular.js:1767:12)
http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=openevent&p1=Error%…bootstrap%20(http%3A%2F%2Flocalhost%3A8080%2Flibs%2Fangular.js%3A1767%3A12)
```

Steps to reproduce:
```
docker run -p 80:5000 dengyiping/open-event-orga-server
git clone git@github.com:fossasia/open-event-webapp.git
cd open-event-webapp
npm install
node_modules/.bin/bower update
node_modules/.bin/bower gulp
http://localhost:8080
```

**Comment by aayusharora** [comment]
@oren , check this #188

**Comment by oren** [comment]
thanks!
