### ISSUE TITLE
Docker build is not working

### ISSUE THREAD

**Issue by Kreijstal** [fossasia/open-event-webapp#1987]
**Actual Behaviour**
The current docker build is not working

**Expected Behaviour**
It should work as is
<!—-State here what the feature should enable the user to do.-—>

**Steps to reproduce it**
Attempt to create a docker image and run it
<!—-Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.-—>

**Log for the issue**

<!—-Provide console logs for the issue here-—>
```
webapp_1       | > open-event-webapp@2.0.0 start /usr/src/app                                                                                                   [0/1878]
webapp_1       | > node src/app.js
webapp_1       |
webapp_1       | /usr/src/app/src/app.js:104
webapp_1       |     job.save(async function(err, currentJob) {
webapp_1       |              ^^^^^
webapp_1       |
webapp_1       | SyntaxError: missing ) after argument list
webapp_1       |     at createScript (vm.js:56:10)
webapp_1       |     at Object.runInThisContext (vm.js:97:10)
webapp_1       |     at Module._compile (module.js:549:28)
webapp_1       |     at Object.Module._extensions..js (module.js:586:10)
webapp_1       |     at Module.load (module.js:494:32)
webapp_1       |     at tryModuleLoad (module.js:453:12)
webapp_1       |     at Function.Module._load (module.js:445:3)
webapp_1       |     at Module.runMain (module.js:611:10)
webapp_1       |     at run (bootstrap_node.js:394:7)
webapp_1       |     at startup (bootstrap_node.js:160:9)
webapp_1       |
webapp_1       | npm ERR! Linux 4.13.0-45-generic
webapp_1       | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
webapp_1       | npm ERR! node v6.14.3
webapp_1       | npm ERR! npm  v3.10.10
webapp_1       | npm ERR! code ELIFECYCLE
webapp_1       | npm ERR! open-event-webapp@2.0.0 start: `node src/app.js`
webapp_1       | npm ERR! Exit status 1
webapp_1       | npm ERR!
webapp_1       | npm ERR! Failed at the open-event-webapp@2.0.0 start script 'node src/app.js'.
webapp_1       | npm ERR! Make sure you have the latest version of node.js and npm installed.
webapp_1       | npm ERR! If you do, this is most likely a problem with the open-event-webapp package,
webapp_1       | npm ERR! not with npm itself.
webapp_1       | npm ERR! Tell the author that this fails on your system:
webapp_1       | npm ERR!     node src/app.js
webapp_1       | npm ERR! You can get information on how to open an issue for this project with:
webapp_1       | npm ERR!     npm bugs open-event-webapp
webapp_1       | npm ERR! Or if that isn't available, you can get their info via:
webapp_1       | npm ERR!     npm owner ls open-event-webapp
webapp_1       | npm ERR! There is likely additional logging output above.
webapp_1       |
webapp_1       | npm ERR! Please include the following file with any support request:
webapp_1       | npm ERR!     /usr/src/app/npm-debug.log
```

**Would you like to work on the issue?**
Yeah!
<!—-Let us know if this issue should be assigned to you or tell us who you think could help to solve this issue.-—>

**Comment by v4ld3rr4m4** [comment]
What is the status of container docker?  I try to run but maybe the container not exist redis , I am trying to fix insallling and commit a new image but generate some Node errs.
